export const article = [
    {
      title: "Consectetur anim mollit et voluptate nisi consequat nostrud duis minim veniam aliquip consequat.",
      description: "Voluptate tempor mollit ex reprehenderit Lorem laboris nostrud Lorem laboris mollit ullamco quis labore nostrud. Occaecat et velit sunt sit consequat Lorem magna quis Lorem sint officia labore velit. Incididunt elit proident quis esse veniam eiusmod proident proident dolor velit ut exercitation nulla ut.",
      tags: ["",],
      introParagraph: "",
      st1Paragraph: "",
      nd2Paragraph: "",
      rd3Paragraph: "",
      conclusionParagraph: "",
      references: "",
      bibliographie: "",
      imageUrl: [],
      link:"#",
    },
    {
      title: "Ipsum reprehenderit et consectetur amet.",
      description: "Nulla aliqua eiusmod dolor occaecat reprehenderit eiusmod cillum elit magna culpa. Tempor cillum deserunt excepteur aliquip elit ad proident deserunt officia sint consectetur reprehenderit nisi enim. Laborum labore in ipsum in eiusmod Lorem minim reprehenderit aliqua. Excepteur laborum duis ullamco velit labore eu occaecat aliqua.",
      tags: ["",],
      introParagraph: "",
      st1Paragraph: "",
      nd2Paragraph: "",
      rd3Paragraph: "",
      conclusionParagraph: "",
      references: "",
      bibliographie: "",
      imageUrl: [],
      link:"#",
    },
] as const;